# Generated by Django 5.1.1 on 2024-10-11 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposTorneio',
            fields=[
                ('ttor_id', models.AutoField(primary_key=True, serialize=False)),
                ('ttor_tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usu_id', models.AutoField(primary_key=True, serialize=False)),
                ('usu_nome_completo', models.CharField(max_length=255)),
                ('usu_data_nascimento', models.DateField(blank=True, null=True)),
                ('usu_telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('usu_nickname', models.CharField(blank=True, max_length=25, null=True)),
                ('usu_email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('tor_id', models.AutoField(primary_key=True, serialize=False)),
                ('tor_nome_torneio', models.CharField(max_length=255)),
                ('tor_quant_participantes', models.IntegerField()),
                ('tor_ativo', models.BooleanField(default=True)),
                ('tor_data_criacao', models.DateField(auto_now_add=True)),
                ('tor_descricao', models.CharField(max_length=255)),
                ('tor_data_inicio', models.DateField(blank=True, null=True)),
                ('tor_data_inicio_inscricao', models.DateField(blank=True, null=True)),
                ('tor_data_fim_inscricao', models.DateField(blank=True, null=True)),
                ('tor_tipo_torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyarena.tipostorneio')),
                ('tor_usu_criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('res_resultado', models.IntegerField()),
                ('res_usu_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('res_tor_torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyarena.torneio')),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoTorneio',
            fields=[
                ('ins_id', models.AutoField(primary_key=True, serialize=False)),
                ('ins_usu_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ins_tor_torneios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyarena.torneio')),
            ],
        ),
        migrations.CreateModel(
            name='TorneioRodada',
            fields=[
                ('rod_id', models.AutoField(primary_key=True, serialize=False)),
                ('rod_rodada', models.IntegerField()),
                ('rod_tor_torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyarena.torneio')),
            ],
        ),
        migrations.CreateModel(
            name='PartidaRodada',
            fields=[
                ('par_id', models.AutoField(primary_key=True, serialize=False)),
                ('par_resultado', models.BooleanField()),
                ('par_usu_participante_dois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partida_participante_dois', to=settings.AUTH_USER_MODEL)),
                ('par_usu_participante_um', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partida_participante_um', to=settings.AUTH_USER_MODEL)),
                ('par_rod_rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyarena.torneiorodada')),
            ],
        ),
    ]
