# Generated by Django 5.1.1 on 2024-10-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyarena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
