# Generated by Django 5.1.1 on 2024-10-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyarena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='tor_data_fim_inscricao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torneio',
            name='tor_data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torneio',
            name='tor_data_inicio_inscricao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
