# Generated by Django 5.1.1 on 2024-10-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyarena', '0002_torneio_tor_data_fim_inscricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneio',
            name='tor_usu_criador',
        ),
    ]
