# Generated by Django 5.0.2 on 2024-03-02 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyArenaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_street', message='A rua deve conter apenas números.', regex='^[A-Za-z]*$')]),
        ),
    ]
