# Generated by Django 4.2.7 on 2024-03-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyArenaApp', '0002_alter_address_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
    ]
